# Generated by Django 4.0.3 on 2022-04-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_activity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatches',
            name='staff_to',
            field=models.CharField(default='todos', max_length=200),
        ),
    ]
