# Generated by Django 4.0.3 on 2022-04-15 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_staff_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='name',
            new_name='username',
        ),
    ]
