# Generated by Django 4.0.3 on 2022-04-15 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_name_staff_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='staff',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='username',
            new_name='name',
        ),
    ]
