# Generated by Django 4.0.3 on 2022-04-16 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_task_assigned_to_alter_client_advice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='register_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
