# Generated by Django 4.0.3 on 2022-04-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_client_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='paid_unitl',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='client',
            name='pay_in',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
