# Generated by Django 4.0.3 on 2022-04-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_clientpayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='charges',
            field=models.FloatField(default=0),
        ),
    ]
