# Generated by Django 4.0.3 on 2022-04-26 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_client_charges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorypayments',
            name='quantity',
        ),
    ]
