# Generated by Django 4.0.3 on 2022-04-27 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_inventorypayments_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='pay_in',
        ),
        migrations.RemoveField(
            model_name='clientpayments',
            name='membership_time',
        ),
    ]
