# Generated by Django 4.0.3 on 2022-05-01 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_client_pay_in_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='paid_unitl',
            new_name='paid_until',
        ),
    ]
