# Generated by Django 4.0.3 on 2022-05-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_rename_paid_unitl_client_paid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='paid_until',
            field=models.DateTimeField(),
        ),
    ]
