# Generated by Django 4.0.3 on 2022-05-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_client_paid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='paid_until',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
